silverstripe/silverstripe-campaign-admin

tests/php/CampaignAdminListTest.php, tests/php/CampaignAdminTest.php
Fix unit tests broken by https://github.com/silverstripe/silverstripe-campaign-admin/pull/3
=> Fix unit tests

.travis.yml, phpunit.xml.dist
See https://github.com/silverstripe/silverstripe-installer/pull/168
=> Update test configuration

client/dist/js/bundle.js, client/src/containers/CampaignAdmin/CampaignAdminItem.js
Issue: https://github.com/silverstripe/silverstripe-framework/issues/6430
=> Fix asset thumbnail size

client/dist/js/bundle.js, client/src/containers/CampaignAdmin/CampaignAdmin.js, src/CampaignAdmin.php
Required for https://github.com/silverstripe/silverstripe-framework/issues/6141
=> API split DetailEditForm into campaignEditForm and campaignCreateForm

client/dist/js/bundle.js, client/src/containers/CampaignAdmin/CampaignAdmin.js, client/src/containers/CampaignAdmin/CampaignAdminList.js
Follow up from https://github.com/silverstripe/silverstripe-admin/pull/33
=> Fix config sections look up

webpack-dev.config.js
They're not being used and they're breaking things.
=> BUGFIX: Get rid of special dev plugins

src/CampaignAdmin.php
Relies on
https://github.com/silverstripe/silverstripe-framework/pull/7065
=> FIX: Use new resource references

src/CampaignAdmin.php
Issue: https://github.com/silverstripe/silverstripe-admin/issues/90
=> Enable unsaved change confirmation

.upgrade.yml, src/CampaignAdminList.php
Part of https://github.com/silverstripe/silverstripe-framework/issues/7104
=> Update code for upgrader

lang/en.yml, src/CampaignAdmin.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/6862
=> Fix unnamespaced i18n keys

src/CampaignAdmin.php, src/CampaignAdminExtension.php
Parent issue https://github.com/silverstripe/silverstripe-admin/issues/299
=> Update usages of deprecated API

.eslintrc.js, package.json, yarn.lock
Resolves https://github.com/silverstripe/silverstripe-framework/issues/7563
=> Use new ESLint config package

package.json, yarn.lock
To `0.0.2` to reflect @flamerohr 's changes
=> Upgrade eslint-config

src/AddToCampaignHandler.php
Issue: https://github.com/silverstripe/silverstripe-campaign-admin/issues/57
=> FIX issue where there's no error for duplicate name

src/CampaignAdmin.php, tests/behat/features/populate-campaigns.feature
Requires https://github.com/silverstripe/silverstripe-admin/pull/474
Fixes #91
=> BUG Fix gridfield being cut off on sides

src/CampaignAdmin.php
Partial fix of https://github.com/silverstripe/silverstripe-framework/issues/5594
=> FIX text/json is not a valid mimetype

src/CampaignAdmin.php
Issue: https://github.com/silverstripe/silverstripe-framework/issues/8424
=> FIX Replace usage of Convert JSON methods with json_encode and json_decode

.travis.yml
See https://github.com/silverstripe/silverstripe-framework/issues/8556
=> API Bump minimum PHP version to 7.1

package.json, yarn.lock
* https://github.com/silverstripeltd/product-issues/issues/48
=> Upgrade dependnecies

src/AddToCampaignHandler.php
=> Do not include inferred changesets in dropdown

.travis.yml, client/lang/sl.js, client/lang/src/sl.json, lang/sl.yml
* https://github.com/silverstripeltd/product-issues/issues/177
=> Merge up 1.6 branch + update travis to target x-dev branches

.travis.yml
This should allow artifacts to be uploaded when a Behat failure is encountered.
=> MNT Align behat artifact upload step with asset-admin

.travis.yml
A part of [PHP8 support initiative](https://github.com/silverstripe/silverstripe-framework/issues/9704)
=> MNT PHP8 support

behat.yml, client/src/components/IntroScreen/tests/IntroScreen-test.js
Part of https://github.com/silverstripe/silverstripe-admin/issues/1126
=> FIX Address regression caused by reactstrap upgrade

behat.yml
Fixing failing builds see https://travis-ci.com/github/silverstripe/silverstripe-campaign-admin/jobs/412142189
=> MNT quote scalar

tests/behat/features/populate-campaigns.feature, tests/behat/src/FixtureContext.php
Issues https://github.com/silverstripe/silverstripe-behat-extension/issues/200
=> MNT Use behat-extension function for clicking elements

tests/behat/features/manage-campaigns.feature
Issue https://github.com/silverstripeltd/product-issues/issues/473
=> MNT Update behat tests

package.json, yarn.lock
Issue https://github.com/silverstripeltd/product-issues/issues/505
=> DEP Update JS dependencies

.github/workflows/update-js-deps.yml
Issue https://github.com/silverstripeltd/product-issues/issues/367
=> MNT Remove extra space from workflow
